#+OPTIONS: LaTeX:t          Do the right thing automatically (MathJax)
#+OPTIONS: LaTeX:dvipng     Force using dvipng images
#+OPTIONS: LaTeX:nil        Do not process LaTeX fragments at all
#+OPTIONS: LaTeX:verbatim   Verbatim export, for jsMath or so
#+ATTR_HTML: width="10in"

% org-export-with-LaTeX-fragments



README.org --- description



Copyright (C) 2012 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>



  This file is part of pneumolinelm.

  pneumolinelm is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  pneumolinelm is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with pneumolinelm.  If not, see <http://www.gnu.org/licenses/>.



* Keywords:
  pneumolinelm pneumo valve linear electro motor actuator 



* Description:
  проект создания клапана со следующими характеристиками
** обязательные параметры
  - низкая цена
  - низкий вес
  - относительно высокие давления (2-10атм.) здесь скорее всего
    ограничение в насосе и трубочках которые я смогу раздобыть, и
    безопасно использовать
  - низкое энергопотребление при переключении. Например было бы
    замечательно если U=5V I<40mA (возможности микроконтроллера без
    цепей усиления)
  - высокое быстродействие клапана для ШИМ

** желательные параметры
  - возможность приоткрывать клапан на контролируемое значение
  - долгий срок службы
  - отсутствие шума (через тонкие отверстия воздух будет шипеть)

** вероятны минусы ?
  - безопасность: Я не очень представляю что произойдёт при
    разгерметизации. Клапан может вылететь - поэтому плотная одежда и
    защита лица и особенно глаз (очки).
  - скорость потока газа через клапан будет низкой из-за малого
    диаметра отверстия 
  - при сильных вибрациях и ударах, клапан будет открываться
  - зазор между ротором и статором в электродвигателе будет всегда
    один и составляет доли миллиметра - значит вибромотор скорее всего
    более экономичен. Ведь в моём случае шарик находится посреди
    трубки и нужно его оттянуть до края этой трубки диаметр которой
    примрно 6.5mm (диаметр трубок из дозатора для жидкого мыла: 6.5mm
    либо 5.3mm ) значит расстояние от центра шара до наружней стенки
    3.25mm
  - магнитное поле будет создавать помехи для соседних устройств
    (нужно что-то придумать для пневмоострова)
   


* Usage:
  use it



* History:
  Version 0.1 was created at 2013-02(Feb)-10


* Dependences:

* Принцип действия
  после прочтения статьи Tetsuya AKAGI, Shujiro DOHTA and Shin-ichi
  KATAYAMA "DEVELOPMENT OF SMALL-SIZED FLEXIBLE CONTROL VALVE USING
  VIBRATION MOTOR", в которой исследуется воздушный клапан,
  управляемый вибромотором, у меня возник вопрос не проще ли управлять
  клапаном напрямую?

  в статье управляющий ток -> магнитное поле -> вращение ротора -> колебания эксцентрика -> колебания шарика

  у меня управляющий ток -> магнитное поле -> колебания шарика


  схема клапана в статическом положении [[./drawing/valve.svg]]

  схема клапана при колебании [[./drawing/activity.svg]]

  три варианта расположения катушек индуктивности [[./drawing/inductor.svg]]

* calculation

**  дано:
    R - радиус шара
    r - радиус отверстия
    P - давление
    пренебрежём массой шара
** найти
   f - сила сдвигающая шар

** решение
   F - сила вдавливающая шар
   N - сила реакции опоры
   

   [[./drawing/geometric_calculation.svg]]

   предположим что шар удалось сдвинуть с места на очень малое
   расстояние, тогда шар будет касаться отверстия всего в одной точке
   (вместо трёхмерной - плоская задача).



   
  $P=\frac{F}{S}$ 
  
  площадь отверстия:
  $S=\pi*r^2$
  
  $F=P*S = P*\pi*r^2$

  $R^2 = h^2 + r^2$

  

  треугольник образованный силами FfN подобен треугольнику Rrh. А всё
  из-за того что сила реакции опоры перпендикулярна плоскости опоры
  (точка соприкосновения шара и отверстия) - значит она
  перпендикулярна плоскости шара (вот тут следует сказать про то что
  отверстие возможно слегка мягкое и прогибается под действием шара),
  а линия перпендикулярная поверхности шара проходит через его центр
  как и все силы FfN и линии образующие треугольник Rrh - значит у
  них один угол ⍺.

  следовательно
  
  $\frac{F}{f}=\frac{h}{r}$

  $f=\frac{F*r}{h}=\frac{F*r}{\sqrt{R^2 - r^2}}=\frac{P*\pi*r^3}{\sqrt{R^2 - r^2}}$

  итого:
  $f=\frac{P*\pi*r^3}{\sqrt{R^2 - r^2}}$

